@echo Building GLFW Application...
g++ -c -I. src/Gen1.cpp src/glad.c src/generate.cpp src/window.cpp 
@echo Compilation complete, proceeding to linking...
g++ -o app.exe Gen1.o glad.o generate.o window.o -L. -lglfw3 -lopengl32 -lgdi32
@echo Linking complete, running application...
.\app
